export const halloweenFestivalConfig = {
  slug: "halloween",
  brandUrl: "https://dayticker.net",
  customsNoBottomRadius: true,
  footerVariant: "default",
  theme: {
    bgMain: "#140E17",
    bgHero: "#241626",
    bgSoft: "#2A1720",
    bgCard: "rgba(255, 248, 250, 0.94)",
    textStrong: "#FDF1E6",
    textBody: "#C7B7BA",
    textSoft: "#D2C7CE",
    textOnDark: "#FFE6CC",
    accentPrimary: "#FF9D2E",
    accentStrong: "#FFB14A",
    footerBg: "#120E12",
    lineSoft: "#5C3D2E",
    lineCard: "#EED9DE",
    noteColor: "#EAC5B6",
    shadowSoft: "0 20px 48px rgba(20, 14, 23, 0.34)",
    bodyAccent: "rgba(224, 122, 42, 0.24)",
    heroOrb: "rgba(141, 90, 60, 0.42)",
    pageOrb: "rgba(42, 23, 32, 0.52)",
    heroTitle: "#FDF1E6",
    sectionTitle: "#FFB14A",
    sectionKicker: "#EAC5B6",
    badgeBg: "#3C2523",
    badgeMutedBg: "#2D1A21",
    habitBg: "#FFF8FA",
    habitBorder: "#6A3148",
    habitTitle: "#7A2443",
    footerTopLine: "#4A3A43",
  },
  images: {
    hero: {
      avif: "./assets/hero-halloween.avif",
      width: 952,
      height: 392,
    },
    origins: {
      avif: "./assets/origins-halloween.avif",
      width: 1400,
      height: 560,
    },
    customs: [
      {
        avif: "./assets/custom-halloween-1.avif",
        width: 792,
        height: 380,
      },
      {
        avif: "./assets/custom-halloween-2.avif",
        width: 792,
        height: 380,
      },
    ],
  },
  translations: {
    zh: {
      pageTitle: "DayTicker",
      pageDescription: "万圣节专题网页，介绍万圣节的历史来源、节日玩法与社区互动文化。",
      heroEyebrow: "万圣节专题 · Halloween Feature",
      heroTitle: "南瓜灯亮起时，城市夜色也开始讲怪诞与童趣的故事",
      heroLead:
        "从装扮游行、南瓜雕刻到糖果敲门，这一页把万圣节写成一场兼具戏剧感与社区参与感的夜间节庆体验。",
      heroBadges: [
        { text: "节日起源", href: "#origins", variant: "primary" },
        { text: "节日玩法", href: "#customs", variant: "muted" },
        { text: "每年 10 月 31 日", variant: "primary" },
        { text: "Playful · Spooky · Social", variant: "muted" },
      ],
      heroImageAlt: "万圣节夜晚街区中的南瓜灯与节日装饰场景",
      originsEyebrow: "节日起源 · Origins",
      originsTitle: "万圣节从何而来？",
      originsIntro:
        "万圣节源于古老的季节节庆与民俗传统，后来发展为以装扮、社区互动和夜间庆祝为核心的文化节日。它让人们在秋夜里用游戏感与想象力连接彼此。",
      originsImageAlt: "万圣节南瓜灯与夜间街景",
      originsCaption: "南瓜灯、服装与社区夜游，共同构成万圣节最鲜明的节日语言。",
      originCardTitle: "历史线索",
      originCardBody:
        "从古代秋收季尾声的仪式，到现代城市里的节庆文化，万圣节逐步形成了“装扮、互动、共享夜晚”的公共表达方式。",
      originPatternText: "节日从仪式演化为社区活动，核心始终是让陌生人也能在同一夜晚产生连接。",
      historyCardTitle: "现代语境",
      historyCardBody:
        "今天的万圣节兼具娱乐与参与感：孩子敲门要糖、年轻人变装聚会、家庭布置门廊，城市与社区都能成为节日舞台。",
      historyPoint1: "社区互动：Trick-or-Treat 让邻里关系更有温度",
      historyPoint2: "夜间节庆：灯光、装扮与故事感塑造独特氛围",
      customsEyebrow: "万圣节玩法",
      customsTitle: "万圣节通常怎么玩？",
      customsIntro:
        "南瓜灯与主题装饰、变装派对与巡游、Trick-or-Treat、恐怖片和故事夜，构成了万圣节最常见也最有参与感的节日体验。",
      habit1Title: "① 南瓜灯与主题装饰",
      habit1Body: "把门廊、街区和商店布置成节日场景，让夜晚从视觉上先进入“万圣节时间”。",
      habit2Title: "② 变装派对与巡游",
      habit2Body: "通过角色扮演和公开巡游，把想象力转化成可见的节日表演。",
      habit3Title: "③ Trick-or-Treat 与故事夜",
      habit3Body: "孩子与家庭在社区中建立互动，观影和都市传说则让夜晚更完整。",
      customDragonBoatAlt: "万圣节街区灯饰与夜间巡游氛围",
      customZongziAlt: "万圣节派对现场与家庭互动场景",
      footerTitle: "DayTicker · 万圣节 Halloween",
      footerSubtitle: "用一页可漫游的节日叙事，串联南瓜灯、糖果与夜色中的社区欢庆时刻。",
      footerOrigins: "节日起源",
      footerCustoms: "节日玩法",
      footerCulture: "夜色氛围",
      footerSite: "DayTicker 官网",
    },
    en: {
      pageTitle: "DayTicker",
      pageDescription:
        "A Halloween feature page covering its cultural roots, signature activities, and community night-time celebrations.",
      heroEyebrow: "Halloween Feature",
      heroTitle: "When jack-o'-lanterns glow, the city night starts telling playful spooky stories",
      heroLead:
        "From costume parades and pumpkin carving to trick-or-treat routes, this page frames Halloween as a night festival full of theatrical mood and neighborhood participation.",
      heroBadges: [
        { text: "Origins", href: "#origins", variant: "primary" },
        { text: "Activities", href: "#customs", variant: "muted" },
        { text: "October 31 Every Year", variant: "primary" },
        { text: "Playful · Spooky · Social", variant: "muted" },
      ],
      heroImageAlt: "Halloween night street with jack-o'-lanterns and festive decor",
      originsEyebrow: "Festival Origins · Origins",
      originsTitle: "Where does Halloween come from?",
      originsIntro:
        "Halloween grew from ancient seasonal customs into a modern cultural festival centered on costumes, neighborhood interaction, and night-time celebration. It connects people through imagination and play in autumn evenings.",
      originsImageAlt: "Pumpkin lanterns and Halloween night streetscape",
      originsCaption:
        "Lanterns, costumes, and neighborhood night walks define Halloween's most recognizable visual language.",
      originCardTitle: "Historical Threads",
      originCardBody:
        "From end-of-harvest seasonal rituals to urban celebrations, Halloween evolved into a public expression of dressing up, social interaction, and shared night-time experiences.",
      originPatternText:
        "The forms changed across time, but the core stayed the same: creating connection through one shared festive night.",
      historyCardTitle: "Modern Context",
      historyCardBody:
        "Today Halloween blends entertainment and participation: kids trick-or-treat, friends host costume parties, and families decorate porches, turning neighborhoods into festival stages.",
      historyPoint1: "Neighborhood warmth: trick-or-treat strengthens local interaction",
      historyPoint2: "Night aesthetics: lights, costumes, and stories shape the atmosphere",
      customsEyebrow: "Halloween Activities",
      customsTitle: "How do people usually celebrate Halloween?",
      customsIntro:
        "Jack-o'-lantern decor, costume parties and parades, trick-or-treating, horror movies, and story nights together form the most common and engaging Halloween experiences.",
      habit1Title: "1. Jack-o'-Lantern Decor",
      habit1Body:
        "Decorate porches, streets, and storefronts to shift the whole neighborhood into Halloween mode.",
      habit2Title: "2. Costume Parties and Parades",
      habit2Body:
        "Turn imagination into visible celebration through role-play, costumes, and public festive gatherings.",
      habit3Title: "3. Trick-or-Treat and Story Nights",
      habit3Body:
        "Family routes, candy stops, movies, and local legends complete the night's social ritual.",
      customDragonBoatAlt: "Halloween-lit neighborhood and night parade atmosphere",
      customZongziAlt: "Halloween party and family interaction scene",
      footerTitle: "DayTicker · Halloween",
      footerSubtitle:
        "A navigable festival story connecting lanterns, candy routes, and shared neighborhood nights.",
      footerOrigins: "Origins",
      footerCustoms: "Activities",
      footerCulture: "Night Mood",
      footerSite: "DayTicker Official Site",
    },
  },
};
